os:
- linux

language: php

before_script:
- composer install

jobs:
  include:
  - script: ./vendor/bin/phpcs --standard="./vendor/squizlabs/php_codesniffer/src/Standards/PSR12/ruleset.xml" ./src ./tests
  - script: ./vendor/bin/phpmd ./src text ./phpmd.xml
  - script: ./vendor/bin/phpunit

php:
- 7.0
- 7.1
- 7.2
- master

matrix:
  fast_finish: true

notifications:
  email: true
